<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\FeatureSet;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.protobuf.FeatureSet.EnumType</code>
 */
class EnumType
{
    /**
     * Generated from protobuf enum <code>ENUM_TYPE_UNSPECIFIED = 0;</code>
     */
    const ENUM_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>ENUM_TYPE_OPEN = 1;</code>
     */
    const ENUM_TYPE_OPEN = 1;
    /**
     * Generated from protobuf enum <code>ENUM_TYPE_CLOSED = 2;</code>
     */
    const ENUM_TYPE_CLOSED = 2;

    private static $valueToName = [
        self::ENUM_TYPE_UNSPECIFIED => 'ENUM_TYPE_UNSPECIFIED',
        self::ENUM_TYPE_OPEN => 'ENUM_TYPE_OPEN',
        self::ENUM_TYPE_CLOSED => 'ENUM_TYPE_CLOSED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

