<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\FeatureSet;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.protobuf.FeatureSet.JsonFormat</code>
 */
class JsonFormat
{
    /**
     * Generated from protobuf enum <code>JSON_FORMAT_UNSPECIFIED = 0;</code>
     */
    const JSON_FORMAT_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>JSON_FORMAT_ALLOW = 1;</code>
     */
    const JSON_FORMAT_ALLOW = 1;
    /**
     * Generated from protobuf enum <code>JSON_FORMAT_LEGACY_BEST_EFFORT = 2;</code>
     */
    const JSON_FORMAT_LEGACY_BEST_EFFORT = 2;

    private static $valueToName = [
        self::JSON_FORMAT_UNSPECIFIED => 'JSON_FORMAT_UNSPECIFIED',
        self::JSON_FORMAT_ALLOW => 'JSON_FORMAT_ALLOW',
        self::JSON_FORMAT_LEGACY_BEST_EFFORT => 'JSON_FORMAT_LEGACY_BEST_EFFORT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

