version: "3"

logs:
  encoding: json

rpc:
  listen: "tcp://127.0.0.1:6001"

grpc:
  listen: "tcp://127.0.0.1:9001"
  tls:
    key: "certs/local.key"
    cert: "certs/local.crt"
  proto:
    - "proto/basic/v1/basic.proto"
    - "proto/basic/service/v1/service.proto"
    - "proto/io/cloudevents/v1/cloudevents.proto"
  pool:
    num_workers: 4
    max_jobs: 0
    max_queue_size: 10
    allocate_timeout: 60s
    reset_timeout: 60s
    stream_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 60s
      exec_ttl: 0s
      max_worker_memory: 0

server:
  command: "php app.php"
  relay: pipes
