<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Describes a message type.
 *
 * Generated from protobuf message <code>google.protobuf.DescriptorProto</code>
 */
class DescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto field = 2 [json_name = "field"];</code>
     */
    private $field;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto extension = 6 [json_name = "extension"];</code>
     */
    private $extension;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto nested_type = 3 [json_name = "nestedType"];</code>
     */
    private $nested_type;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4 [json_name = "enumType"];</code>
     */
    private $enum_type;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5 [json_name = "extensionRange"];</code>
     */
    private $extension_range;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8 [json_name = "oneofDecl"];</code>
     */
    private $oneof_decl;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.MessageOptions options = 7 [json_name = "options"];</code>
     */
    protected $options = null;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9 [json_name = "reservedRange"];</code>
     */
    private $reserved_range;
    /**
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     *
     * Generated from protobuf field <code>repeated string reserved_name = 10 [json_name = "reservedName"];</code>
     */
    private $reserved_name;
    /**
     * Support for `export` and `local` keywords on enums.
     *
     * Generated from protobuf field <code>optional .google.protobuf.SymbolVisibility visibility = 11 [json_name = "visibility"];</code>
     */
    protected $visibility = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type \Google\Protobuf\Proto\FieldDescriptorProto[] $field
     *     @type \Google\Protobuf\Proto\FieldDescriptorProto[] $extension
     *     @type \Google\Protobuf\Proto\DescriptorProto[] $nested_type
     *     @type \Google\Protobuf\Proto\EnumDescriptorProto[] $enum_type
     *     @type \Google\Protobuf\Proto\DescriptorProto\ExtensionRange[] $extension_range
     *     @type \Google\Protobuf\Proto\OneofDescriptorProto[] $oneof_decl
     *     @type \Google\Protobuf\Proto\MessageOptions $options
     *     @type \Google\Protobuf\Proto\DescriptorProto\ReservedRange[] $reserved_range
     *     @type string[] $reserved_name
     *           Reserved field names, which may not be used by fields in the same message.
     *           A given name may only be reserved once.
     *     @type int $visibility
     *           Support for `export` and `local` keywords on enums.
     * }
     */
    public function __construct($data = NULL) {
        \Google\Protobuf\GPBMetadata\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto field = 2 [json_name = "field"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\FieldDescriptorProto>
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto field = 2 [json_name = "field"];</code>
     * @param \Google\Protobuf\Proto\FieldDescriptorProto[] $var
     * @return $this
     */
    public function setField($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\FieldDescriptorProto::class);
        $this->field = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto extension = 6 [json_name = "extension"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\FieldDescriptorProto>
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto extension = 6 [json_name = "extension"];</code>
     * @param \Google\Protobuf\Proto\FieldDescriptorProto[] $var
     * @return $this
     */
    public function setExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\FieldDescriptorProto::class);
        $this->extension = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto nested_type = 3 [json_name = "nestedType"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\DescriptorProto>
     */
    public function getNestedType()
    {
        return $this->nested_type;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto nested_type = 3 [json_name = "nestedType"];</code>
     * @param \Google\Protobuf\Proto\DescriptorProto[] $var
     * @return $this
     */
    public function setNestedType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\DescriptorProto::class);
        $this->nested_type = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4 [json_name = "enumType"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\EnumDescriptorProto>
     */
    public function getEnumType()
    {
        return $this->enum_type;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 4 [json_name = "enumType"];</code>
     * @param \Google\Protobuf\Proto\EnumDescriptorProto[] $var
     * @return $this
     */
    public function setEnumType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\EnumDescriptorProto::class);
        $this->enum_type = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5 [json_name = "extensionRange"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\DescriptorProto\ExtensionRange>
     */
    public function getExtensionRange()
    {
        return $this->extension_range;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5 [json_name = "extensionRange"];</code>
     * @param \Google\Protobuf\Proto\DescriptorProto\ExtensionRange[] $var
     * @return $this
     */
    public function setExtensionRange($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\DescriptorProto\ExtensionRange::class);
        $this->extension_range = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8 [json_name = "oneofDecl"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\OneofDescriptorProto>
     */
    public function getOneofDecl()
    {
        return $this->oneof_decl;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8 [json_name = "oneofDecl"];</code>
     * @param \Google\Protobuf\Proto\OneofDescriptorProto[] $var
     * @return $this
     */
    public function setOneofDecl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\OneofDescriptorProto::class);
        $this->oneof_decl = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.MessageOptions options = 7 [json_name = "options"];</code>
     * @return \Google\Protobuf\Proto\MessageOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.MessageOptions options = 7 [json_name = "options"];</code>
     * @param \Google\Protobuf\Proto\MessageOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Proto\MessageOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9 [json_name = "reservedRange"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\DescriptorProto\ReservedRange>
     */
    public function getReservedRange()
    {
        return $this->reserved_range;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9 [json_name = "reservedRange"];</code>
     * @param \Google\Protobuf\Proto\DescriptorProto\ReservedRange[] $var
     * @return $this
     */
    public function setReservedRange($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\DescriptorProto\ReservedRange::class);
        $this->reserved_range = $arr;

        return $this;
    }

    /**
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     *
     * Generated from protobuf field <code>repeated string reserved_name = 10 [json_name = "reservedName"];</code>
     * @return RepeatedField<string>
     */
    public function getReservedName()
    {
        return $this->reserved_name;
    }

    /**
     * Reserved field names, which may not be used by fields in the same message.
     * A given name may only be reserved once.
     *
     * Generated from protobuf field <code>repeated string reserved_name = 10 [json_name = "reservedName"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setReservedName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->reserved_name = $arr;

        return $this;
    }

    /**
     * Support for `export` and `local` keywords on enums.
     *
     * Generated from protobuf field <code>optional .google.protobuf.SymbolVisibility visibility = 11 [json_name = "visibility"];</code>
     * @return int
     */
    public function getVisibility()
    {
        return isset($this->visibility) ? $this->visibility : 0;
    }

    public function hasVisibility()
    {
        return isset($this->visibility);
    }

    public function clearVisibility()
    {
        unset($this->visibility);
    }

    /**
     * Support for `export` and `local` keywords on enums.
     *
     * Generated from protobuf field <code>optional .google.protobuf.SymbolVisibility visibility = 11 [json_name = "visibility"];</code>
     * @param int $var
     * @return $this
     */
    public function setVisibility($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Proto\SymbolVisibility::class);
        $this->visibility = $var;

        return $this;
    }

}

