<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>google.protobuf.ExtensionRangeOptions</code>
 */
class ExtensionRangeOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * The parser stores options it doesn't recognize here. See above.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];</code>
     */
    private $uninterpreted_option;
    /**
     * For external users: DO NOT USE. We are in the process of open sourcing
     * extension declaration and executing internal cleanups before it can be
     * used externally.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = OPTION_RETENTION_SOURCE];</code>
     */
    private $declaration;
    /**
     * Any features defined in the specific edition.
     *
     * Generated from protobuf field <code>optional .google.protobuf.FeatureSet features = 50 [json_name = "features"];</code>
     */
    protected $features = null;
    /**
     * The verification state of the range.
     * TODO: flip the default to DECLARATION once all empty ranges
     * are marked as UNVERIFIED.
     *
     * Generated from protobuf field <code>optional .google.protobuf.ExtensionRangeOptions.VerificationState verification = 3 [json_name = "verification", retention = OPTION_RETENTION_SOURCE];</code>
     */
    protected $verification = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Proto\UninterpretedOption[] $uninterpreted_option
     *           The parser stores options it doesn't recognize here. See above.
     *     @type \Google\Protobuf\Proto\ExtensionRangeOptions\Declaration[] $declaration
     *           For external users: DO NOT USE. We are in the process of open sourcing
     *           extension declaration and executing internal cleanups before it can be
     *           used externally.
     *     @type \Google\Protobuf\Proto\FeatureSet $features
     *           Any features defined in the specific edition.
     *     @type int $verification
     *           The verification state of the range.
     *           TODO: flip the default to DECLARATION once all empty ranges
     *           are marked as UNVERIFIED.
     * }
     */
    public function __construct($data = NULL) {
        \Google\Protobuf\GPBMetadata\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * The parser stores options it doesn't recognize here. See above.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\UninterpretedOption>
     */
    public function getUninterpretedOption()
    {
        return $this->uninterpreted_option;
    }

    /**
     * The parser stores options it doesn't recognize here. See above.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];</code>
     * @param \Google\Protobuf\Proto\UninterpretedOption[] $var
     * @return $this
     */
    public function setUninterpretedOption($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\UninterpretedOption::class);
        $this->uninterpreted_option = $arr;

        return $this;
    }

    /**
     * For external users: DO NOT USE. We are in the process of open sourcing
     * extension declaration and executing internal cleanups before it can be
     * used externally.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = OPTION_RETENTION_SOURCE];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\ExtensionRangeOptions\Declaration>
     */
    public function getDeclaration()
    {
        return $this->declaration;
    }

    /**
     * For external users: DO NOT USE. We are in the process of open sourcing
     * extension declaration and executing internal cleanups before it can be
     * used externally.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.ExtensionRangeOptions.Declaration declaration = 2 [json_name = "declaration", retention = OPTION_RETENTION_SOURCE];</code>
     * @param \Google\Protobuf\Proto\ExtensionRangeOptions\Declaration[] $var
     * @return $this
     */
    public function setDeclaration($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\ExtensionRangeOptions\Declaration::class);
        $this->declaration = $arr;

        return $this;
    }

    /**
     * Any features defined in the specific edition.
     *
     * Generated from protobuf field <code>optional .google.protobuf.FeatureSet features = 50 [json_name = "features"];</code>
     * @return \Google\Protobuf\Proto\FeatureSet|null
     */
    public function getFeatures()
    {
        return $this->features;
    }

    public function hasFeatures()
    {
        return isset($this->features);
    }

    public function clearFeatures()
    {
        unset($this->features);
    }

    /**
     * Any features defined in the specific edition.
     *
     * Generated from protobuf field <code>optional .google.protobuf.FeatureSet features = 50 [json_name = "features"];</code>
     * @param \Google\Protobuf\Proto\FeatureSet $var
     * @return $this
     */
    public function setFeatures($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Proto\FeatureSet::class);
        $this->features = $var;

        return $this;
    }

    /**
     * The verification state of the range.
     * TODO: flip the default to DECLARATION once all empty ranges
     * are marked as UNVERIFIED.
     *
     * Generated from protobuf field <code>optional .google.protobuf.ExtensionRangeOptions.VerificationState verification = 3 [json_name = "verification", retention = OPTION_RETENTION_SOURCE];</code>
     * @return int
     */
    public function getVerification()
    {
        return isset($this->verification) ? $this->verification : 0;
    }

    public function hasVerification()
    {
        return isset($this->verification);
    }

    public function clearVerification()
    {
        unset($this->verification);
    }

    /**
     * The verification state of the range.
     * TODO: flip the default to DECLARATION once all empty ranges
     * are marked as UNVERIFIED.
     *
     * Generated from protobuf field <code>optional .google.protobuf.ExtensionRangeOptions.VerificationState verification = 3 [json_name = "verification", retention = OPTION_RETENTION_SOURCE];</code>
     * @param int $var
     * @return $this
     */
    public function setVerification($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Proto\ExtensionRangeOptions\VerificationState::class);
        $this->verification = $var;

        return $this;
    }

}

