<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Describes a complete .proto file.
 *
 * Generated from protobuf message <code>google.protobuf.FileDescriptorProto</code>
 */
class FileDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * file name, relative to root of source tree
     *
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     */
    protected $name = null;
    /**
     * e.g. "foo", "foo.bar", etc.
     *
     * Generated from protobuf field <code>optional string package = 2 [json_name = "package"];</code>
     */
    protected $package = null;
    /**
     * Names of files imported by this file.
     *
     * Generated from protobuf field <code>repeated string dependency = 3 [json_name = "dependency"];</code>
     */
    private $dependency;
    /**
     * Indexes of the public imported files in the dependency list above.
     *
     * Generated from protobuf field <code>repeated int32 public_dependency = 10 [json_name = "publicDependency"];</code>
     */
    private $public_dependency;
    /**
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     *
     * Generated from protobuf field <code>repeated int32 weak_dependency = 11 [json_name = "weakDependency"];</code>
     */
    private $weak_dependency;
    /**
     * Names of files imported by this file purely for the purpose of providing
     * option extensions. These are excluded from the dependency list above.
     *
     * Generated from protobuf field <code>repeated string option_dependency = 15 [json_name = "optionDependency"];</code>
     */
    private $option_dependency;
    /**
     * All top-level definitions in this file.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];</code>
     */
    private $message_type;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];</code>
     */
    private $enum_type;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];</code>
     */
    private $service;
    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];</code>
     */
    private $extension;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.FileOptions options = 8 [json_name = "options"];</code>
     */
    protected $options = null;
    /**
     * This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     *
     * Generated from protobuf field <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];</code>
     */
    protected $source_code_info = null;
    /**
     * The syntax of the proto file.
     * The supported values are "proto2", "proto3", and "editions".
     * If `edition` is present, this value must be "editions".
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     *
     * Generated from protobuf field <code>optional string syntax = 12 [json_name = "syntax"];</code>
     */
    protected $syntax = null;
    /**
     * The edition of the proto file.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Edition edition = 14 [json_name = "edition"];</code>
     */
    protected $edition = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           file name, relative to root of source tree
     *     @type string $package
     *           e.g. "foo", "foo.bar", etc.
     *     @type string[] $dependency
     *           Names of files imported by this file.
     *     @type int[] $public_dependency
     *           Indexes of the public imported files in the dependency list above.
     *     @type int[] $weak_dependency
     *           Indexes of the weak imported files in the dependency list.
     *           For Google-internal migration only. Do not use.
     *     @type string[] $option_dependency
     *           Names of files imported by this file purely for the purpose of providing
     *           option extensions. These are excluded from the dependency list above.
     *     @type \Google\Protobuf\Proto\DescriptorProto[] $message_type
     *           All top-level definitions in this file.
     *     @type \Google\Protobuf\Proto\EnumDescriptorProto[] $enum_type
     *     @type \Google\Protobuf\Proto\ServiceDescriptorProto[] $service
     *     @type \Google\Protobuf\Proto\FieldDescriptorProto[] $extension
     *     @type \Google\Protobuf\Proto\FileOptions $options
     *     @type \Google\Protobuf\Proto\SourceCodeInfo $source_code_info
     *           This field contains optional information about the original source code.
     *           You may safely remove this entire field without harming runtime
     *           functionality of the descriptors -- the information is needed only by
     *           development tools.
     *     @type string $syntax
     *           The syntax of the proto file.
     *           The supported values are "proto2", "proto3", and "editions".
     *           If `edition` is present, this value must be "editions".
     *           WARNING: This field should only be used by protobuf plugins or special
     *           cases like the proto compiler. Other uses are discouraged and
     *           developers should rely on the protoreflect APIs for their client language.
     *     @type int $edition
     *           The edition of the proto file.
     *           WARNING: This field should only be used by protobuf plugins or special
     *           cases like the proto compiler. Other uses are discouraged and
     *           developers should rely on the protoreflect APIs for their client language.
     * }
     */
    public function __construct($data = NULL) {
        \Google\Protobuf\GPBMetadata\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * file name, relative to root of source tree
     *
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * file name, relative to root of source tree
     *
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * e.g. "foo", "foo.bar", etc.
     *
     * Generated from protobuf field <code>optional string package = 2 [json_name = "package"];</code>
     * @return string
     */
    public function getPackage()
    {
        return isset($this->package) ? $this->package : '';
    }

    public function hasPackage()
    {
        return isset($this->package);
    }

    public function clearPackage()
    {
        unset($this->package);
    }

    /**
     * e.g. "foo", "foo.bar", etc.
     *
     * Generated from protobuf field <code>optional string package = 2 [json_name = "package"];</code>
     * @param string $var
     * @return $this
     */
    public function setPackage($var)
    {
        GPBUtil::checkString($var, True);
        $this->package = $var;

        return $this;
    }

    /**
     * Names of files imported by this file.
     *
     * Generated from protobuf field <code>repeated string dependency = 3 [json_name = "dependency"];</code>
     * @return RepeatedField<string>
     */
    public function getDependency()
    {
        return $this->dependency;
    }

    /**
     * Names of files imported by this file.
     *
     * Generated from protobuf field <code>repeated string dependency = 3 [json_name = "dependency"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setDependency($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dependency = $arr;

        return $this;
    }

    /**
     * Indexes of the public imported files in the dependency list above.
     *
     * Generated from protobuf field <code>repeated int32 public_dependency = 10 [json_name = "publicDependency"];</code>
     * @return RepeatedField<int>
     */
    public function getPublicDependency()
    {
        return $this->public_dependency;
    }

    /**
     * Indexes of the public imported files in the dependency list above.
     *
     * Generated from protobuf field <code>repeated int32 public_dependency = 10 [json_name = "publicDependency"];</code>
     * @param int[] $var
     * @return $this
     */
    public function setPublicDependency($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->public_dependency = $arr;

        return $this;
    }

    /**
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     *
     * Generated from protobuf field <code>repeated int32 weak_dependency = 11 [json_name = "weakDependency"];</code>
     * @return RepeatedField<int>
     */
    public function getWeakDependency()
    {
        return $this->weak_dependency;
    }

    /**
     * Indexes of the weak imported files in the dependency list.
     * For Google-internal migration only. Do not use.
     *
     * Generated from protobuf field <code>repeated int32 weak_dependency = 11 [json_name = "weakDependency"];</code>
     * @param int[] $var
     * @return $this
     */
    public function setWeakDependency($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->weak_dependency = $arr;

        return $this;
    }

    /**
     * Names of files imported by this file purely for the purpose of providing
     * option extensions. These are excluded from the dependency list above.
     *
     * Generated from protobuf field <code>repeated string option_dependency = 15 [json_name = "optionDependency"];</code>
     * @return RepeatedField<string>
     */
    public function getOptionDependency()
    {
        return $this->option_dependency;
    }

    /**
     * Names of files imported by this file purely for the purpose of providing
     * option extensions. These are excluded from the dependency list above.
     *
     * Generated from protobuf field <code>repeated string option_dependency = 15 [json_name = "optionDependency"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setOptionDependency($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->option_dependency = $arr;

        return $this;
    }

    /**
     * All top-level definitions in this file.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\DescriptorProto>
     */
    public function getMessageType()
    {
        return $this->message_type;
    }

    /**
     * All top-level definitions in this file.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];</code>
     * @param \Google\Protobuf\Proto\DescriptorProto[] $var
     * @return $this
     */
    public function setMessageType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\DescriptorProto::class);
        $this->message_type = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\EnumDescriptorProto>
     */
    public function getEnumType()
    {
        return $this->enum_type;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];</code>
     * @param \Google\Protobuf\Proto\EnumDescriptorProto[] $var
     * @return $this
     */
    public function setEnumType($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\EnumDescriptorProto::class);
        $this->enum_type = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\ServiceDescriptorProto>
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];</code>
     * @param \Google\Protobuf\Proto\ServiceDescriptorProto[] $var
     * @return $this
     */
    public function setService($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\ServiceDescriptorProto::class);
        $this->service = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];</code>
     * @return RepeatedField<\Google\Protobuf\Proto\FieldDescriptorProto>
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Generated from protobuf field <code>repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];</code>
     * @param \Google\Protobuf\Proto\FieldDescriptorProto[] $var
     * @return $this
     */
    public function setExtension($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Proto\FieldDescriptorProto::class);
        $this->extension = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.FileOptions options = 8 [json_name = "options"];</code>
     * @return \Google\Protobuf\Proto\FileOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.FileOptions options = 8 [json_name = "options"];</code>
     * @param \Google\Protobuf\Proto\FileOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Proto\FileOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     *
     * Generated from protobuf field <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];</code>
     * @return \Google\Protobuf\Proto\SourceCodeInfo|null
     */
    public function getSourceCodeInfo()
    {
        return $this->source_code_info;
    }

    public function hasSourceCodeInfo()
    {
        return isset($this->source_code_info);
    }

    public function clearSourceCodeInfo()
    {
        unset($this->source_code_info);
    }

    /**
     * This field contains optional information about the original source code.
     * You may safely remove this entire field without harming runtime
     * functionality of the descriptors -- the information is needed only by
     * development tools.
     *
     * Generated from protobuf field <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];</code>
     * @param \Google\Protobuf\Proto\SourceCodeInfo $var
     * @return $this
     */
    public function setSourceCodeInfo($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Proto\SourceCodeInfo::class);
        $this->source_code_info = $var;

        return $this;
    }

    /**
     * The syntax of the proto file.
     * The supported values are "proto2", "proto3", and "editions".
     * If `edition` is present, this value must be "editions".
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     *
     * Generated from protobuf field <code>optional string syntax = 12 [json_name = "syntax"];</code>
     * @return string
     */
    public function getSyntax()
    {
        return isset($this->syntax) ? $this->syntax : '';
    }

    public function hasSyntax()
    {
        return isset($this->syntax);
    }

    public function clearSyntax()
    {
        unset($this->syntax);
    }

    /**
     * The syntax of the proto file.
     * The supported values are "proto2", "proto3", and "editions".
     * If `edition` is present, this value must be "editions".
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     *
     * Generated from protobuf field <code>optional string syntax = 12 [json_name = "syntax"];</code>
     * @param string $var
     * @return $this
     */
    public function setSyntax($var)
    {
        GPBUtil::checkString($var, True);
        $this->syntax = $var;

        return $this;
    }

    /**
     * The edition of the proto file.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Edition edition = 14 [json_name = "edition"];</code>
     * @return int
     */
    public function getEdition()
    {
        return isset($this->edition) ? $this->edition : 0;
    }

    public function hasEdition()
    {
        return isset($this->edition);
    }

    public function clearEdition()
    {
        unset($this->edition);
    }

    /**
     * The edition of the proto file.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     *
     * Generated from protobuf field <code>optional .google.protobuf.Edition edition = 14 [json_name = "edition"];</code>
     * @param int $var
     * @return $this
     */
    public function setEdition($var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\Proto\Edition::class);
        $this->edition = $var;

        return $this;
    }

}

