<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Describes a method of a service.
 *
 * Generated from protobuf message <code>google.protobuf.MethodDescriptorProto</code>
 */
class MethodDescriptorProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     */
    protected $name = null;
    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>optional string input_type = 2 [json_name = "inputType"];</code>
     */
    protected $input_type = null;
    /**
     * Generated from protobuf field <code>optional string output_type = 3 [json_name = "outputType"];</code>
     */
    protected $output_type = null;
    /**
     * Generated from protobuf field <code>optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];</code>
     */
    protected $options = null;
    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>optional bool client_streaming = 5 [json_name = "clientStreaming"];</code>
     */
    protected $client_streaming = null;
    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>optional bool server_streaming = 6 [json_name = "serverStreaming"];</code>
     */
    protected $server_streaming = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $input_type
     *           Input and output type names.  These are resolved in the same way as
     *           FieldDescriptorProto.type_name, but must refer to a message type.
     *     @type string $output_type
     *     @type \Google\Protobuf\Proto\MethodOptions $options
     *     @type bool $client_streaming
     *           Identifies if client streams multiple client messages
     *     @type bool $server_streaming
     *           Identifies if server streams multiple server messages
     * }
     */
    public function __construct($data = NULL) {
        \Google\Protobuf\GPBMetadata\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 1 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>optional string input_type = 2 [json_name = "inputType"];</code>
     * @return string
     */
    public function getInputType()
    {
        return isset($this->input_type) ? $this->input_type : '';
    }

    public function hasInputType()
    {
        return isset($this->input_type);
    }

    public function clearInputType()
    {
        unset($this->input_type);
    }

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     *
     * Generated from protobuf field <code>optional string input_type = 2 [json_name = "inputType"];</code>
     * @param string $var
     * @return $this
     */
    public function setInputType($var)
    {
        GPBUtil::checkString($var, True);
        $this->input_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string output_type = 3 [json_name = "outputType"];</code>
     * @return string
     */
    public function getOutputType()
    {
        return isset($this->output_type) ? $this->output_type : '';
    }

    public function hasOutputType()
    {
        return isset($this->output_type);
    }

    public function clearOutputType()
    {
        unset($this->output_type);
    }

    /**
     * Generated from protobuf field <code>optional string output_type = 3 [json_name = "outputType"];</code>
     * @param string $var
     * @return $this
     */
    public function setOutputType($var)
    {
        GPBUtil::checkString($var, True);
        $this->output_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];</code>
     * @return \Google\Protobuf\Proto\MethodOptions|null
     */
    public function getOptions()
    {
        return $this->options;
    }

    public function hasOptions()
    {
        return isset($this->options);
    }

    public function clearOptions()
    {
        unset($this->options);
    }

    /**
     * Generated from protobuf field <code>optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];</code>
     * @param \Google\Protobuf\Proto\MethodOptions $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Proto\MethodOptions::class);
        $this->options = $var;

        return $this;
    }

    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>optional bool client_streaming = 5 [json_name = "clientStreaming"];</code>
     * @return bool
     */
    public function getClientStreaming()
    {
        return isset($this->client_streaming) ? $this->client_streaming : false;
    }

    public function hasClientStreaming()
    {
        return isset($this->client_streaming);
    }

    public function clearClientStreaming()
    {
        unset($this->client_streaming);
    }

    /**
     * Identifies if client streams multiple client messages
     *
     * Generated from protobuf field <code>optional bool client_streaming = 5 [json_name = "clientStreaming"];</code>
     * @param bool $var
     * @return $this
     */
    public function setClientStreaming($var)
    {
        GPBUtil::checkBool($var);
        $this->client_streaming = $var;

        return $this;
    }

    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>optional bool server_streaming = 6 [json_name = "serverStreaming"];</code>
     * @return bool
     */
    public function getServerStreaming()
    {
        return isset($this->server_streaming) ? $this->server_streaming : false;
    }

    public function hasServerStreaming()
    {
        return isset($this->server_streaming);
    }

    public function clearServerStreaming()
    {
        unset($this->server_streaming);
    }

    /**
     * Identifies if server streams multiple server messages
     *
     * Generated from protobuf field <code>optional bool server_streaming = 6 [json_name = "serverStreaming"];</code>
     * @param bool $var
     * @return $this
     */
    public function setServerStreaming($var)
    {
        GPBUtil::checkBool($var);
        $this->server_streaming = $var;

        return $this;
    }

}

