<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto;

use UnexpectedValueException;

/**
 * Describes the 'visibility' of a symbol with respect to the proto import
 * system. Symbols can only be imported when the visibility rules do not prevent
 * it (ex: local symbols cannot be imported).  Visibility modifiers can only set
 * on `message` and `enum` as they are the only types available to be referenced
 * from other files.
 *
 * Protobuf type <code>google.protobuf.SymbolVisibility</code>
 */
class SymbolVisibility
{
    /**
     * Generated from protobuf enum <code>SYMBOL_VISIBILITY_UNSPECIFIED = 0;</code>
     */
    const SYMBOL_VISIBILITY_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>SYMBOL_VISIBILITY_LOCAL = 1;</code>
     */
    const SYMBOL_VISIBILITY_LOCAL = 1;
    /**
     * Generated from protobuf enum <code>SYMBOL_VISIBILITY_EXPORT = 2;</code>
     */
    const SYMBOL_VISIBILITY_EXPORT = 2;

    private static $valueToName = [
        self::SYMBOL_VISIBILITY_UNSPECIFIED => 'SYMBOL_VISIBILITY_UNSPECIFIED',
        self::SYMBOL_VISIBILITY_LOCAL => 'SYMBOL_VISIBILITY_LOCAL',
        self::SYMBOL_VISIBILITY_EXPORT => 'SYMBOL_VISIBILITY_EXPORT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

