<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\FileOptions;

use UnexpectedValueException;

/**
 * Generated classes can be optimized for speed or code size.
 *
 * Protobuf type <code>google.protobuf.FileOptions.OptimizeMode</code>
 */
class OptimizeMode
{
    /**
     * Generated from protobuf enum <code>OPTIMIZE_MODE_UNSPECIFIED = 0;</code>
     */
    const OPTIMIZE_MODE_UNSPECIFIED = 0;
    /**
     * Generate complete code for parsing, serialization,
     *
     * Generated from protobuf enum <code>OPTIMIZE_MODE_SPEED = 1;</code>
     */
    const OPTIMIZE_MODE_SPEED = 1;
    /**
     * etc.
     *
     * Generated from protobuf enum <code>OPTIMIZE_MODE_CODE_SIZE = 2;</code>
     */
    const OPTIMIZE_MODE_CODE_SIZE = 2;
    /**
     * Generate code using MessageLite and the lite runtime.
     *
     * Generated from protobuf enum <code>OPTIMIZE_MODE_LITE_RUNTIME = 3;</code>
     */
    const OPTIMIZE_MODE_LITE_RUNTIME = 3;

    private static $valueToName = [
        self::OPTIMIZE_MODE_UNSPECIFIED => 'OPTIMIZE_MODE_UNSPECIFIED',
        self::OPTIMIZE_MODE_SPEED => 'OPTIMIZE_MODE_SPEED',
        self::OPTIMIZE_MODE_CODE_SIZE => 'OPTIMIZE_MODE_CODE_SIZE',
        self::OPTIMIZE_MODE_LITE_RUNTIME => 'OPTIMIZE_MODE_LITE_RUNTIME',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

