<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\UninterpretedOption;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The name of the uninterpreted option.  Each string represents a segment in
 * a dot-separated name.  is_extension is true iff a segment represents an
 * extension (denoted with parentheses in options specs in .proto files).
 * E.g.,{ ["foo", false], ["bar.baz", true], ["moo", false] } represents
 * "foo.(bar.baz).moo".
 *
 * Generated from protobuf message <code>google.protobuf.UninterpretedOption.NamePart</code>
 */
class NamePart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name_part = 1 [json_name = "namePart"];</code>
     */
    protected $name_part = '';
    /**
     * Generated from protobuf field <code>bool is_extension = 2 [json_name = "isExtension"];</code>
     */
    protected $is_extension = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name_part
     *     @type bool $is_extension
     * }
     */
    public function __construct($data = NULL) {
        \Google\Protobuf\GPBMetadata\Descriptor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name_part = 1 [json_name = "namePart"];</code>
     * @return string
     */
    public function getNamePart()
    {
        return $this->name_part;
    }

    /**
     * Generated from protobuf field <code>string name_part = 1 [json_name = "namePart"];</code>
     * @param string $var
     * @return $this
     */
    public function setNamePart($var)
    {
        GPBUtil::checkString($var, True);
        $this->name_part = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_extension = 2 [json_name = "isExtension"];</code>
     * @return bool
     */
    public function getIsExtension()
    {
        return $this->is_extension;
    }

    /**
     * Generated from protobuf field <code>bool is_extension = 2 [json_name = "isExtension"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIsExtension($var)
    {
        GPBUtil::checkBool($var);
        $this->is_extension = $var;

        return $this;
    }

}

