<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace Grpc\Reflection\v1alpha\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The type name and extension number sent by the client when requesting
 * file_containing_extension.
 *
 * Generated from protobuf message <code>grpc.reflection.v1alpha.ExtensionRequest</code>
 */
class ExtensionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Fully-qualified type name. The format should be <package>.<type>
     *
     * Generated from protobuf field <code>string containing_type = 1 [json_name = "containingType"];</code>
     */
    protected $containing_type = '';
    /**
     * Generated from protobuf field <code>int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     */
    protected $extension_number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $containing_type
     *           Fully-qualified type name. The format should be <package>.<type>
     *     @type int $extension_number
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\Reflection\v1alpha\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Fully-qualified type name. The format should be <package>.<type>
     *
     * Generated from protobuf field <code>string containing_type = 1 [json_name = "containingType"];</code>
     * @return string
     */
    public function getContainingType()
    {
        return $this->containing_type;
    }

    /**
     * Fully-qualified type name. The format should be <package>.<type>
     *
     * Generated from protobuf field <code>string containing_type = 1 [json_name = "containingType"];</code>
     * @param string $var
     * @return $this
     */
    public function setContainingType($var)
    {
        GPBUtil::checkString($var, True);
        $this->containing_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     * @return int
     */
    public function getExtensionNumber()
    {
        return $this->extension_number;
    }

    /**
     * Generated from protobuf field <code>int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     * @param int $var
     * @return $this
     */
    public function setExtensionNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->extension_number = $var;

        return $this;
    }

}

