<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1alpha/reflection.proto

namespace Grpc\Reflection\v1alpha\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Serialized FileDescriptorProto messages sent by the server answering
 * a file_by_filename, file_containing_symbol, or file_containing_extension
 * request.
 *
 * Generated from protobuf message <code>grpc.reflection.v1alpha.FileDescriptorResponse</code>
 */
class FileDescriptorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     *
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     */
    private $file_descriptor_proto;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $file_descriptor_proto
     *           Serialized FileDescriptorProto messages. We avoid taking a dependency on
     *           descriptor.proto, which uses proto2 only features, by making them opaque
     *           bytes instead.
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\Reflection\v1alpha\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     *
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     * @return RepeatedField<string>
     */
    public function getFileDescriptorProto()
    {
        return $this->file_descriptor_proto;
    }

    /**
     * Serialized FileDescriptorProto messages. We avoid taking a dependency on
     * descriptor.proto, which uses proto2 only features, by making them opaque
     * bytes instead.
     *
     * Generated from protobuf field <code>repeated bytes file_descriptor_proto = 1 [json_name = "fileDescriptorProto"];</code>
     * @param string[] $var
     * @return $this
     */
    public function setFileDescriptorProto($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->file_descriptor_proto = $arr;

        return $this;
    }

}

