<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: grpc/reflection/v1alpha/reflection.proto

namespace Grpc\Reflection\v1alpha\Proto;

use Spiral\RoadRunner\GRPC;

interface ServerReflectionInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "grpc.reflection.v1alpha.ServerReflection";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ServerReflectionRequest $in
    * @return ServerReflectionResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ServerReflectionInfo(GRPC\ContextInterface $ctx, ServerReflectionRequest $in): ServerReflectionResponse;
}
