<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/service/v1/service.proto

namespace GRPC\Basic\Service\V1\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>basic.service.v1.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>PROCESS_STATE_UNSPECIFIED = 0;</code>
     */
    const PROCESS_STATE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>PROCESS_STATE_PROCESS = 1;</code>
     */
    const PROCESS_STATE_PROCESS = 1;
    /**
     * Generated from protobuf enum <code>PROCESS_STATE_COMPLETE = 2;</code>
     */
    const PROCESS_STATE_COMPLETE = 2;
    /**
     * Generated from protobuf enum <code>PROCESS_STATE_ERROR = 3;</code>
     */
    const PROCESS_STATE_ERROR = 3;
    /**
     * Generated from protobuf enum <code>PROCESS_STATE_COMPLETE_WITH_ERROR = 4;</code>
     */
    const PROCESS_STATE_COMPLETE_WITH_ERROR = 4;

    private static $valueToName = [
        self::PROCESS_STATE_UNSPECIFIED => 'PROCESS_STATE_UNSPECIFIED',
        self::PROCESS_STATE_PROCESS => 'PROCESS_STATE_PROCESS',
        self::PROCESS_STATE_COMPLETE => 'PROCESS_STATE_COMPLETE',
        self::PROCESS_STATE_ERROR => 'PROCESS_STATE_ERROR',
        self::PROCESS_STATE_COMPLETE_WITH_ERROR => 'PROCESS_STATE_COMPLETE_WITH_ERROR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

