<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/cloudevents/v1/cloudevents.proto

namespace GRPC\Io\CloudEvents\V1\GPBMetadata;

class Cloudevents
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC3\x07\x0A#io/cloudevents/v1/cloudevents.proto\x12\x11io.cloudevents.v1\x1A\x1Fgoogle/protobuf/timestamp.proto\"\xCF\x05\x0A\x0ACloudEvent\x12\x0E\x0A\x02id\x18\x01 \x01(\x09R\x02id\x12\x16\x0A\x06source\x18\x02 \x01(\x09R\x06source\x12!\x0A\x0Cspec_version\x18\x03 \x01(\x09R\x0BspecVersion\x12\x12\x0A\x04type\x18\x04 \x01(\x09R\x04type\x12M\x0A\x0Aattributes\x18\x05 \x03(\x0B2-.io.cloudevents.v1.CloudEvent.AttributesEntryR\x0Aattributes\x12!\x0A\x0Bbinary_data\x18\x06 \x01(\x0CH\x00R\x0AbinaryData\x12\x1D\x0A\x09text_data\x18\x07 \x01(\x09H\x00R\x08textData\x125\x0A\x0Aproto_data\x18\x08 \x01(\x0B2\x14.google.protobuf.AnyH\x00R\x09protoData\x1Au\x0A\x0FAttributesEntry\x12\x10\x0A\x03key\x18\x01 \x01(\x09R\x03key\x12L\x0A\x05value\x18\x02 \x01(\x0B26.io.cloudevents.v1.CloudEvent.CloudEventAttributeValueR\x05value:\x028\x01\x1A\x9A\x02\x0A\x18CloudEventAttributeValue\x12\x1F\x0A\x0Ace_boolean\x18\x01 \x01(\x08H\x00R\x09ceBoolean\x12\x1F\x0A\x0Ace_integer\x18\x02 \x01(\x05H\x00R\x09ceInteger\x12\x1D\x0A\x09ce_string\x18\x03 \x01(\x09H\x00R\x08ceString\x12\x1B\x0A\x08ce_bytes\x18\x04 \x01(\x0CH\x00R\x07ceBytes\x12\x17\x0A\x06ce_uri\x18\x05 \x01(\x09H\x00R\x05ceUri\x12\x1E\x0A\x0Ace_uri_ref\x18\x06 \x01(\x09H\x00R\x08ceUriRef\x12?\x0A\x0Cce_timestamp\x18\x07 \x01(\x0B2\x1A.google.protobuf.TimestampH\x00R\x0BceTimestampB\x06\x0A\x04attrB\x06\x0A\x04data\"H\x0A\x0FCloudEventBatch\x125\x0A\x06events\x18\x01 \x03(\x0B2\x1D.io.cloudevents.v1.CloudEventR\x06eventsBD\xCA\x02\x1CGRPC\\Io\\CloudEvents\\V1\\Proto\xE2\x02\"GRPC\\Io\\CloudEvents\\V1\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

