<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\ExtensionRangeOptions;

use UnexpectedValueException;

/**
 * The verification state of the extension range.
 *
 * Protobuf type <code>google.protobuf.ExtensionRangeOptions.VerificationState</code>
 */
class VerificationState
{
    /**
     * Generated from protobuf enum <code>VERIFICATION_STATE_UNSPECIFIED = 0;</code>
     */
    const VERIFICATION_STATE_UNSPECIFIED = 0;
    /**
     * All the extensions of the range must be declared.
     *
     * Generated from protobuf enum <code>VERIFICATION_STATE_DECLARATION = 1;</code>
     */
    const VERIFICATION_STATE_DECLARATION = 1;
    /**
     * Generated from protobuf enum <code>VERIFICATION_STATE_UNVERIFIED = 2;</code>
     */
    const VERIFICATION_STATE_UNVERIFIED = 2;

    private static $valueToName = [
        self::VERIFICATION_STATE_UNSPECIFIED => 'VERIFICATION_STATE_UNSPECIFIED',
        self::VERIFICATION_STATE_DECLARATION => 'VERIFICATION_STATE_DECLARATION',
        self::VERIFICATION_STATE_UNVERIFIED => 'VERIFICATION_STATE_UNVERIFIED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

