<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/v1/basic.proto

namespace Basic\V1\GPBMetadata;

class Basic
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Basic\Service\V1\GPBMetadata\Service::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD9\x02\x0A\x14basic/v1/basic.proto\x12\x08basic.v12\x84\x02\x0A\x0CBasicService\x12J\x0A\x05Hello\x12\x1E.basic.service.v1.HelloRequest\x1A\x1F.basic.service.v1.HelloResponse\"\x00\x12K\x0A\x04Talk\x12\x1D.basic.service.v1.TalkRequest\x1A\x1E.basic.service.v1.TalkResponse\"\x00(\x010\x01\x12[\x0A\x0ABackground\x12#.basic.service.v1.BackgroundRequest\x1A\$.basic.service.v1.BackgroundResponse\"\x000\x01B(\xCA\x02\x0EBasic\\V1\\Proto\xE2\x02\x14Basic\\V1\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

