<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/cloudevents/v1/cloudevents.proto

namespace GRPC\Io\CloudEvents\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>io.cloudevents.v1.CloudEvent</code>
 */
class CloudEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Required Attributes
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * URI-reference
     *
     * Generated from protobuf field <code>string source = 2 [json_name = "source"];</code>
     */
    protected $source = '';
    /**
     * Generated from protobuf field <code>string spec_version = 3 [json_name = "specVersion"];</code>
     */
    protected $spec_version = '';
    /**
     * Generated from protobuf field <code>string type = 4 [json_name = "type"];</code>
     */
    protected $type = '';
    /**
     * Optional & Extension Attributes
     *
     * Generated from protobuf field <code>map<string, .io.cloudevents.v1.CloudEvent.CloudEventAttributeValue> attributes = 5 [json_name = "attributes"];</code>
     */
    private $attributes;
    protected $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Required Attributes
     *     @type string $source
     *           URI-reference
     *     @type string $spec_version
     *     @type string $type
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *           Optional & Extension Attributes
     *     @type string $binary_data
     *     @type string $text_data
     *     @type \Google\Protobuf\Any $proto_data
     * }
     */
    public function __construct($data = NULL) {
        \GRPC\Io\CloudEvents\V1\GPBMetadata\Cloudevents::initOnce();
        parent::__construct($data);
    }

    /**
     * Required Attributes
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Required Attributes
     *
     * Generated from protobuf field <code>string id = 1 [json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * URI-reference
     *
     * Generated from protobuf field <code>string source = 2 [json_name = "source"];</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * URI-reference
     *
     * Generated from protobuf field <code>string source = 2 [json_name = "source"];</code>
     * @param string $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkString($var, True);
        $this->source = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string spec_version = 3 [json_name = "specVersion"];</code>
     * @return string
     */
    public function getSpecVersion()
    {
        return $this->spec_version;
    }

    /**
     * Generated from protobuf field <code>string spec_version = 3 [json_name = "specVersion"];</code>
     * @param string $var
     * @return $this
     */
    public function setSpecVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->spec_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 4 [json_name = "type"];</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 4 [json_name = "type"];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Optional & Extension Attributes
     *
     * Generated from protobuf field <code>map<string, .io.cloudevents.v1.CloudEvent.CloudEventAttributeValue> attributes = 5 [json_name = "attributes"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Optional & Extension Attributes
     *
     * Generated from protobuf field <code>map<string, .io.cloudevents.v1.CloudEvent.CloudEventAttributeValue> attributes = 5 [json_name = "attributes"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \GRPC\Io\CloudEvents\V1\Proto\CloudEvent\CloudEventAttributeValue::class);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes binary_data = 6 [json_name = "binaryData"];</code>
     * @return string
     */
    public function getBinaryData()
    {
        return $this->readOneof(6);
    }

    public function hasBinaryData()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>bytes binary_data = 6 [json_name = "binaryData"];</code>
     * @param string $var
     * @return $this
     */
    public function setBinaryData($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text_data = 7 [json_name = "textData"];</code>
     * @return string
     */
    public function getTextData()
    {
        return $this->readOneof(7);
    }

    public function hasTextData()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>string text_data = 7 [json_name = "textData"];</code>
     * @param string $var
     * @return $this
     */
    public function setTextData($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any proto_data = 8 [json_name = "protoData"];</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getProtoData()
    {
        return $this->readOneof(8);
    }

    public function hasProtoData()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any proto_data = 8 [json_name = "protoData"];</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setProtoData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("data");
    }

}

