<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/service/v1/service.proto

namespace Basic\Service\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>basic.service.v1.BackgroundResponseEvent</code>
 */
class BackgroundResponseEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.basic.service.v1.State state = 1 [json_name = "state"];</code>
     */
    protected $state = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 2 [json_name = "startedAt"];</code>
     */
    protected $started_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp completed_at = 3 [json_name = "completedAt"];</code>
     */
    protected $completed_at = null;
    /**
     * Generated from protobuf field <code>repeated .basic.service.v1.SomeServiceResponse responses = 4 [json_name = "responses"];</code>
     */
    private $responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type \Google\Protobuf\Timestamp $started_at
     *     @type \Google\Protobuf\Timestamp $completed_at
     *     @type \Basic\Service\V1\Proto\SomeServiceResponse[] $responses
     * }
     */
    public function __construct($data = NULL) {
        \Basic\Service\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.basic.service.v1.State state = 1 [json_name = "state"];</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.basic.service.v1.State state = 1 [json_name = "state"];</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Basic\Service\V1\Proto\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 2 [json_name = "startedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 2 [json_name = "startedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp completed_at = 3 [json_name = "completedAt"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCompletedAt()
    {
        return $this->completed_at;
    }

    public function hasCompletedAt()
    {
        return isset($this->completed_at);
    }

    public function clearCompletedAt()
    {
        unset($this->completed_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp completed_at = 3 [json_name = "completedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCompletedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->completed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .basic.service.v1.SomeServiceResponse responses = 4 [json_name = "responses"];</code>
     * @return RepeatedField<\Basic\Service\V1\Proto\SomeServiceResponse>
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * Generated from protobuf field <code>repeated .basic.service.v1.SomeServiceResponse responses = 4 [json_name = "responses"];</code>
     * @param \Basic\Service\V1\Proto\SomeServiceResponse[] $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basic\Service\V1\Proto\SomeServiceResponse::class);
        $this->responses = $arr;

        return $this;
    }

}

