<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/service/v1/service.proto

namespace Basic\Service\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>basic.service.v1.BackgroundRequest</code>
 */
class BackgroundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 processes = 1 [json_name = "processes"];</code>
     */
    protected $processes = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $processes
     * }
     */
    public function __construct($data = NULL) {
        \Basic\Service\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 processes = 1 [json_name = "processes"];</code>
     * @return int|string
     */
    public function getProcesses()
    {
        return $this->processes;
    }

    /**
     * Generated from protobuf field <code>int64 processes = 1 [json_name = "processes"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setProcesses($var)
    {
        GPBUtil::checkInt64($var);
        $this->processes = $var;

        return $this;
    }

}

