<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/service/v1/service.proto

namespace Basic\Service\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>basic.service.v1.HelloResponse</code>
 */
class HelloResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.cloudevents.v1.CloudEvent cloud_event = 1 [json_name = "cloudEvent"];</code>
     */
    protected $cloud_event = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\CloudEvents\V1\Proto\CloudEvent $cloud_event
     * }
     */
    public function __construct($data = NULL) {
        \Basic\Service\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.cloudevents.v1.CloudEvent cloud_event = 1 [json_name = "cloudEvent"];</code>
     * @return \Io\CloudEvents\V1\Proto\CloudEvent|null
     */
    public function getCloudEvent()
    {
        return $this->cloud_event;
    }

    public function hasCloudEvent()
    {
        return isset($this->cloud_event);
    }

    public function clearCloudEvent()
    {
        unset($this->cloud_event);
    }

    /**
     * Generated from protobuf field <code>.io.cloudevents.v1.CloudEvent cloud_event = 1 [json_name = "cloudEvent"];</code>
     * @param \Io\CloudEvents\V1\Proto\CloudEvent $var
     * @return $this
     */
    public function setCloudEvent($var)
    {
        GPBUtil::checkMessage($var, \Io\CloudEvents\V1\Proto\CloudEvent::class);
        $this->cloud_event = $var;

        return $this;
    }

}

