<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: basic/service/v1/service.proto

namespace Basic\Service\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>basic.service.v1.SomeServiceResponses</code>
 */
class SomeServiceResponses extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .basic.service.v1.SomeServiceResponse responses = 1 [json_name = "responses"];</code>
     */
    private $responses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basic\Service\V1\Proto\SomeServiceResponse[] $responses
     * }
     */
    public function __construct($data = NULL) {
        \Basic\Service\V1\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .basic.service.v1.SomeServiceResponse responses = 1 [json_name = "responses"];</code>
     * @return RepeatedField<\Basic\Service\V1\Proto\SomeServiceResponse>
     */
    public function getResponses()
    {
        return $this->responses;
    }

    /**
     * Generated from protobuf field <code>repeated .basic.service.v1.SomeServiceResponse responses = 1 [json_name = "responses"];</code>
     * @param \Basic\Service\V1\Proto\SomeServiceResponse[] $var
     * @return $this
     */
    public function setResponses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basic\Service\V1\Proto\SomeServiceResponse::class);
        $this->responses = $arr;

        return $this;
    }

}

