<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1/reflection.proto

namespace Grpc\Reflection\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The error code and error message sent by the server when an error occurs.
 *
 * Generated from protobuf message <code>grpc.reflection.v1.ErrorResponse</code>
 */
class ErrorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * This field uses the error codes defined in grpc::StatusCode.
     *
     * Generated from protobuf field <code>int32 error_code = 1 [json_name = "errorCode"];</code>
     */
    protected $error_code = 0;
    /**
     * Generated from protobuf field <code>string error_message = 2 [json_name = "errorMessage"];</code>
     */
    protected $error_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error_code
     *           This field uses the error codes defined in grpc::StatusCode.
     *     @type string $error_message
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\Reflection\V1\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * This field uses the error codes defined in grpc::StatusCode.
     *
     * Generated from protobuf field <code>int32 error_code = 1 [json_name = "errorCode"];</code>
     * @return int
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * This field uses the error codes defined in grpc::StatusCode.
     *
     * Generated from protobuf field <code>int32 error_code = 1 [json_name = "errorCode"];</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

}

