<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1/reflection.proto

namespace Grpc\Reflection\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A list of extension numbers sent by the server answering
 * all_extension_numbers_of_type request.
 *
 * Generated from protobuf message <code>grpc.reflection.v1.ExtensionNumberResponse</code>
 */
class ExtensionNumberResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Full name of the base type, including the package name. The format
     * is <package>.<type>
     *
     * Generated from protobuf field <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     */
    protected $base_type_name = '';
    /**
     * Generated from protobuf field <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     */
    private $extension_number;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $base_type_name
     *           Full name of the base type, including the package name. The format
     *           is <package>.<type>
     *     @type int[] $extension_number
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\Reflection\V1\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Full name of the base type, including the package name. The format
     * is <package>.<type>
     *
     * Generated from protobuf field <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     * @return string
     */
    public function getBaseTypeName()
    {
        return $this->base_type_name;
    }

    /**
     * Full name of the base type, including the package name. The format
     * is <package>.<type>
     *
     * Generated from protobuf field <code>string base_type_name = 1 [json_name = "baseTypeName"];</code>
     * @param string $var
     * @return $this
     */
    public function setBaseTypeName($var)
    {
        GPBUtil::checkString($var, True);
        $this->base_type_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     * @return RepeatedField<int>
     */
    public function getExtensionNumber()
    {
        return $this->extension_number;
    }

    /**
     * Generated from protobuf field <code>repeated int32 extension_number = 2 [json_name = "extensionNumber"];</code>
     * @param int[] $var
     * @return $this
     */
    public function setExtensionNumber($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->extension_number = $arr;

        return $this;
    }

}

