<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1/reflection.proto

namespace Grpc\Reflection\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * A list of ServiceResponse sent by the server answering list_services request.
 *
 * Generated from protobuf message <code>grpc.reflection.v1.ListServiceResponse</code>
 */
class ListServiceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     *
     * Generated from protobuf field <code>repeated .grpc.reflection.v1.ServiceResponse service = 1 [json_name = "service"];</code>
     */
    private $service;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Grpc\Reflection\V1\Proto\ServiceResponse[] $service
     *           The information of each service may be expanded in the future, so we use
     *           ServiceResponse message to encapsulate it.
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\Reflection\V1\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     *
     * Generated from protobuf field <code>repeated .grpc.reflection.v1.ServiceResponse service = 1 [json_name = "service"];</code>
     * @return RepeatedField<\Grpc\Reflection\V1\Proto\ServiceResponse>
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     *
     * Generated from protobuf field <code>repeated .grpc.reflection.v1.ServiceResponse service = 1 [json_name = "service"];</code>
     * @param \Grpc\Reflection\V1\Proto\ServiceResponse[] $var
     * @return $this
     */
    public function setService($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Grpc\Reflection\V1\Proto\ServiceResponse::class);
        $this->service = $arr;

        return $this;
    }

}

