<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc/reflection/v1/reflection.proto

namespace Grpc\Reflection\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * The message sent by the server to answer ServerReflectionInfo method.
 *
 * Generated from protobuf message <code>grpc.reflection.v1.ServerReflectionResponse</code>
 */
class ServerReflectionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string valid_host = 1 [json_name = "validHost"];</code>
     */
    protected $valid_host = '';
    /**
     * Generated from protobuf field <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2 [json_name = "originalRequest"];</code>
     */
    protected $original_request = null;
    protected $message_response;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $valid_host
     *     @type \Grpc\Reflection\V1\Proto\ServerReflectionRequest $original_request
     *     @type \Grpc\Reflection\V1\Proto\FileDescriptorResponse $file_descriptor_response
     *           This message is used to answer file_by_filename, file_containing_symbol,
     *           file_containing_extension requests with transitive dependencies.
     *           As the repeated label is not allowed in oneof fields, we use a
     *           FileDescriptorResponse message to encapsulate the repeated fields.
     *           The reflection service is allowed to avoid sending FileDescriptorProtos
     *           that were previously sent in response to earlier requests in the stream.
     *     @type \Grpc\Reflection\V1\Proto\ExtensionNumberResponse $all_extension_numbers_response
     *           This message is used to answer all_extension_numbers_of_type requests.
     *     @type \Grpc\Reflection\V1\Proto\ListServiceResponse $list_services_response
     *           This message is used to answer list_services requests.
     *     @type \Grpc\Reflection\V1\Proto\ErrorResponse $error_response
     *           This message is used when an error occurs.
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\Reflection\V1\GPBMetadata\Reflection::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string valid_host = 1 [json_name = "validHost"];</code>
     * @return string
     */
    public function getValidHost()
    {
        return $this->valid_host;
    }

    /**
     * Generated from protobuf field <code>string valid_host = 1 [json_name = "validHost"];</code>
     * @param string $var
     * @return $this
     */
    public function setValidHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->valid_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2 [json_name = "originalRequest"];</code>
     * @return \Grpc\Reflection\V1\Proto\ServerReflectionRequest|null
     */
    public function getOriginalRequest()
    {
        return $this->original_request;
    }

    public function hasOriginalRequest()
    {
        return isset($this->original_request);
    }

    public function clearOriginalRequest()
    {
        unset($this->original_request);
    }

    /**
     * Generated from protobuf field <code>.grpc.reflection.v1.ServerReflectionRequest original_request = 2 [json_name = "originalRequest"];</code>
     * @param \Grpc\Reflection\V1\Proto\ServerReflectionRequest $var
     * @return $this
     */
    public function setOriginalRequest($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Reflection\V1\Proto\ServerReflectionRequest::class);
        $this->original_request = $var;

        return $this;
    }

    /**
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4 [json_name = "fileDescriptorResponse"];</code>
     * @return \Grpc\Reflection\V1\Proto\FileDescriptorResponse|null
     */
    public function getFileDescriptorResponse()
    {
        return $this->readOneof(4);
    }

    public function hasFileDescriptorResponse()
    {
        return $this->hasOneof(4);
    }

    /**
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies.
     * As the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.FileDescriptorResponse file_descriptor_response = 4 [json_name = "fileDescriptorResponse"];</code>
     * @param \Grpc\Reflection\V1\Proto\FileDescriptorResponse $var
     * @return $this
     */
    public function setFileDescriptorResponse($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Reflection\V1\Proto\FileDescriptorResponse::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * This message is used to answer all_extension_numbers_of_type requests.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5 [json_name = "allExtensionNumbersResponse"];</code>
     * @return \Grpc\Reflection\V1\Proto\ExtensionNumberResponse|null
     */
    public function getAllExtensionNumbersResponse()
    {
        return $this->readOneof(5);
    }

    public function hasAllExtensionNumbersResponse()
    {
        return $this->hasOneof(5);
    }

    /**
     * This message is used to answer all_extension_numbers_of_type requests.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.ExtensionNumberResponse all_extension_numbers_response = 5 [json_name = "allExtensionNumbersResponse"];</code>
     * @param \Grpc\Reflection\V1\Proto\ExtensionNumberResponse $var
     * @return $this
     */
    public function setAllExtensionNumbersResponse($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Reflection\V1\Proto\ExtensionNumberResponse::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * This message is used to answer list_services requests.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6 [json_name = "listServicesResponse"];</code>
     * @return \Grpc\Reflection\V1\Proto\ListServiceResponse|null
     */
    public function getListServicesResponse()
    {
        return $this->readOneof(6);
    }

    public function hasListServicesResponse()
    {
        return $this->hasOneof(6);
    }

    /**
     * This message is used to answer list_services requests.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.ListServiceResponse list_services_response = 6 [json_name = "listServicesResponse"];</code>
     * @param \Grpc\Reflection\V1\Proto\ListServiceResponse $var
     * @return $this
     */
    public function setListServicesResponse($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Reflection\V1\Proto\ListServiceResponse::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * This message is used when an error occurs.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.ErrorResponse error_response = 7 [json_name = "errorResponse"];</code>
     * @return \Grpc\Reflection\V1\Proto\ErrorResponse|null
     */
    public function getErrorResponse()
    {
        return $this->readOneof(7);
    }

    public function hasErrorResponse()
    {
        return $this->hasOneof(7);
    }

    /**
     * This message is used when an error occurs.
     *
     * Generated from protobuf field <code>.grpc.reflection.v1.ErrorResponse error_response = 7 [json_name = "errorResponse"];</code>
     * @param \Grpc\Reflection\V1\Proto\ErrorResponse $var
     * @return $this
     */
    public function setErrorResponse($var)
    {
        GPBUtil::checkMessage($var, \Grpc\Reflection\V1\Proto\ErrorResponse::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessageResponse()
    {
        return $this->whichOneof("message_response");
    }

}

