<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\GeneratedCodeInfo\Annotation;

use UnexpectedValueException;

/**
 * Represents the identified object's effect on the element in the original
 * .proto file.
 *
 * Protobuf type <code>google.protobuf.GeneratedCodeInfo.Annotation.Semantic</code>
 */
class Semantic
{
    /**
     * There is no effect or the effect is indescribable.
     *
     * Generated from protobuf enum <code>SEMANTIC_UNSPECIFIED = 0;</code>
     */
    const SEMANTIC_UNSPECIFIED = 0;
    /**
     * The element is set or otherwise mutated.
     *
     * Generated from protobuf enum <code>SEMANTIC_SET = 1;</code>
     */
    const SEMANTIC_SET = 1;
    /**
     * An alias to the element is returned.
     *
     * Generated from protobuf enum <code>SEMANTIC_ALIAS = 2;</code>
     */
    const SEMANTIC_ALIAS = 2;

    private static $valueToName = [
        self::SEMANTIC_UNSPECIFIED => 'SEMANTIC_UNSPECIFIED',
        self::SEMANTIC_SET => 'SEMANTIC_SET',
        self::SEMANTIC_ALIAS => 'SEMANTIC_ALIAS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

