<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/cloudevents/v1/cloudevents.proto

namespace Io\CloudEvents\V1\Proto\CloudEvent;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>io.cloudevents.v1.CloudEvent.CloudEventAttributeValue</code>
 */
class CloudEventAttributeValue extends \Google\Protobuf\Internal\Message
{
    protected $attr;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ce_boolean
     *     @type int $ce_integer
     *     @type string $ce_string
     *     @type string $ce_bytes
     *     @type string $ce_uri
     *     @type string $ce_uri_ref
     *     @type \Google\Protobuf\Timestamp $ce_timestamp
     * }
     */
    public function __construct($data = NULL) {
        \Io\CloudEvents\V1\GPBMetadata\Cloudevents::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool ce_boolean = 1 [json_name = "ceBoolean"];</code>
     * @return bool
     */
    public function getCeBoolean()
    {
        return $this->readOneof(1);
    }

    public function hasCeBoolean()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>bool ce_boolean = 1 [json_name = "ceBoolean"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCeBoolean($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ce_integer = 2 [json_name = "ceInteger"];</code>
     * @return int
     */
    public function getCeInteger()
    {
        return $this->readOneof(2);
    }

    public function hasCeInteger()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>int32 ce_integer = 2 [json_name = "ceInteger"];</code>
     * @param int $var
     * @return $this
     */
    public function setCeInteger($var)
    {
        GPBUtil::checkInt32($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ce_string = 3 [json_name = "ceString"];</code>
     * @return string
     */
    public function getCeString()
    {
        return $this->readOneof(3);
    }

    public function hasCeString()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>string ce_string = 3 [json_name = "ceString"];</code>
     * @param string $var
     * @return $this
     */
    public function setCeString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes ce_bytes = 4 [json_name = "ceBytes"];</code>
     * @return string
     */
    public function getCeBytes()
    {
        return $this->readOneof(4);
    }

    public function hasCeBytes()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bytes ce_bytes = 4 [json_name = "ceBytes"];</code>
     * @param string $var
     * @return $this
     */
    public function setCeBytes($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ce_uri = 5 [json_name = "ceUri"];</code>
     * @return string
     */
    public function getCeUri()
    {
        return $this->readOneof(5);
    }

    public function hasCeUri()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>string ce_uri = 5 [json_name = "ceUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setCeUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ce_uri_ref = 6 [json_name = "ceUriRef"];</code>
     * @return string
     */
    public function getCeUriRef()
    {
        return $this->readOneof(6);
    }

    public function hasCeUriRef()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>string ce_uri_ref = 6 [json_name = "ceUriRef"];</code>
     * @param string $var
     * @return $this
     */
    public function setCeUriRef($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp ce_timestamp = 7 [json_name = "ceTimestamp"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCeTimestamp()
    {
        return $this->readOneof(7);
    }

    public function hasCeTimestamp()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp ce_timestamp = 7 [json_name = "ceTimestamp"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCeTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAttr()
    {
        return $this->whichOneof("attr");
    }

}

