<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: io/cloudevents/v1/cloudevents.proto

namespace Io\CloudEvents\V1\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>io.cloudevents.v1.CloudEventBatch</code>
 */
class CloudEventBatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .io.cloudevents.v1.CloudEvent events = 1 [json_name = "events"];</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\CloudEvents\V1\Proto\CloudEvent[] $events
     * }
     */
    public function __construct($data = NULL) {
        \Io\CloudEvents\V1\GPBMetadata\Cloudevents::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .io.cloudevents.v1.CloudEvent events = 1 [json_name = "events"];</code>
     * @return RepeatedField<\Io\CloudEvents\V1\Proto\CloudEvent>
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .io.cloudevents.v1.CloudEvent events = 1 [json_name = "events"];</code>
     * @param \Io\CloudEvents\V1\Proto\CloudEvent[] $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\CloudEvents\V1\Proto\CloudEvent::class);
        $this->events = $arr;

        return $this;
    }

}

