<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\FieldOptions;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.protobuf.FieldOptions.CType</code>
 */
class CType
{
    /**
     * Generated from protobuf enum <code>C_TYPE_UNSPECIFIED = 0;</code>
     */
    const C_TYPE_UNSPECIFIED = 0;
    /**
     * Default mode.
     *
     * Generated from protobuf enum <code>C_TYPE_STRING = 1;</code>
     */
    const C_TYPE_STRING = 1;
    /**
     * The option [ctype=CORD] may be applied to a non-repeated field of type
     * "bytes". It indicates that in C++, the data should be stored in a Cord
     * instead of a string.  For very large strings, this may reduce memory
     * fragmentation. It may also allow better performance when parsing from a
     * Cord, or when parsing with aliasing enabled, as the parsed Cord may then
     * alias the original buffer.
     *
     * Generated from protobuf enum <code>C_TYPE_CORD = 2;</code>
     */
    const C_TYPE_CORD = 2;
    /**
     * Generated from protobuf enum <code>C_TYPE_STRING_PIECE = 3;</code>
     */
    const C_TYPE_STRING_PIECE = 3;

    private static $valueToName = [
        self::C_TYPE_UNSPECIFIED => 'C_TYPE_UNSPECIFIED',
        self::C_TYPE_STRING => 'C_TYPE_STRING',
        self::C_TYPE_CORD => 'C_TYPE_CORD',
        self::C_TYPE_STRING_PIECE => 'C_TYPE_STRING_PIECE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

