<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\FieldOptions;

use UnexpectedValueException;

/**
 * Protobuf type <code>google.protobuf.FieldOptions.JSType</code>
 */
class JSType
{
    /**
     * Generated from protobuf enum <code>JS_TYPE_UNDEFINED = 0;</code>
     */
    const JS_TYPE_UNDEFINED = 0;
    /**
     * Use the default type.
     *
     * Generated from protobuf enum <code>JS_TYPE_NORMAL = 1;</code>
     */
    const JS_TYPE_NORMAL = 1;
    /**
     * Use JavaScript strings.
     *
     * Generated from protobuf enum <code>JS_TYPE_STRING = 2;</code>
     */
    const JS_TYPE_STRING = 2;
    /**
     * Use JavaScript numbers.
     *
     * Generated from protobuf enum <code>JS_TYPE_NUMBER = 3;</code>
     */
    const JS_TYPE_NUMBER = 3;

    private static $valueToName = [
        self::JS_TYPE_UNDEFINED => 'JS_TYPE_UNDEFINED',
        self::JS_TYPE_NORMAL => 'JS_TYPE_NORMAL',
        self::JS_TYPE_STRING => 'JS_TYPE_STRING',
        self::JS_TYPE_NUMBER => 'JS_TYPE_NUMBER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

