<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/protobuf/descriptor.proto

namespace Google\Protobuf\Proto\FieldOptions;

use UnexpectedValueException;

/**
 * This indicates the types of entities that the field may apply to when used
 * as an option. If it is unset, then the field may be freely used as an
 * option on any kind of entity.
 *
 * Protobuf type <code>google.protobuf.FieldOptions.OptionTargetType</code>
 */
class OptionTargetType
{
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_UNSPECIFIED = 0;</code>
     */
    const OPTION_TARGET_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_FILE = 1;</code>
     */
    const OPTION_TARGET_TYPE_FILE = 1;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_EXTENSION_RANGE = 2;</code>
     */
    const OPTION_TARGET_TYPE_EXTENSION_RANGE = 2;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_MESSAGE = 3;</code>
     */
    const OPTION_TARGET_TYPE_MESSAGE = 3;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_FIELD = 4;</code>
     */
    const OPTION_TARGET_TYPE_FIELD = 4;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_ONEOF = 5;</code>
     */
    const OPTION_TARGET_TYPE_ONEOF = 5;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_ENUM = 6;</code>
     */
    const OPTION_TARGET_TYPE_ENUM = 6;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_ENUM_ENTRY = 7;</code>
     */
    const OPTION_TARGET_TYPE_ENUM_ENTRY = 7;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_SERVICE = 8;</code>
     */
    const OPTION_TARGET_TYPE_SERVICE = 8;
    /**
     * Generated from protobuf enum <code>OPTION_TARGET_TYPE_METHOD = 9;</code>
     */
    const OPTION_TARGET_TYPE_METHOD = 9;

    private static $valueToName = [
        self::OPTION_TARGET_TYPE_UNSPECIFIED => 'OPTION_TARGET_TYPE_UNSPECIFIED',
        self::OPTION_TARGET_TYPE_FILE => 'OPTION_TARGET_TYPE_FILE',
        self::OPTION_TARGET_TYPE_EXTENSION_RANGE => 'OPTION_TARGET_TYPE_EXTENSION_RANGE',
        self::OPTION_TARGET_TYPE_MESSAGE => 'OPTION_TARGET_TYPE_MESSAGE',
        self::OPTION_TARGET_TYPE_FIELD => 'OPTION_TARGET_TYPE_FIELD',
        self::OPTION_TARGET_TYPE_ONEOF => 'OPTION_TARGET_TYPE_ONEOF',
        self::OPTION_TARGET_TYPE_ENUM => 'OPTION_TARGET_TYPE_ENUM',
        self::OPTION_TARGET_TYPE_ENUM_ENTRY => 'OPTION_TARGET_TYPE_ENUM_ENTRY',
        self::OPTION_TARGET_TYPE_SERVICE => 'OPTION_TARGET_TYPE_SERVICE',
        self::OPTION_TARGET_TYPE_METHOD => 'OPTION_TARGET_TYPE_METHOD',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

